//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Company
    {
        public int Id { get; set; }
        public string UName { get; set; }
        public string Pwd { get; set; }
        public string Email { get; set; }
        public string SystemName { get; set; }
        public string WebSite { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string Office { get; set; }
        public string Head { get; set; }
        public string Logo { get; set; }
        public string Moblie { get; set; }
        public string QQ { get; set; }
        public Nullable<int> Sex { get; set; }
        public int State { get; set; }
        public string CopanyMsg { get; set; }
        public System.DateTime InTime { get; set; }
        public string Rec_Forum_Index { get; set; }
        public System.DateTime Rec_Forum_Index_Time { get; set; }
        public string Rec_Index { get; set; }
        public System.DateTime Rec_Index_Time { get; set; }
        public Nullable<short> DelFlag { get; set; }
    }
}
