//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class GameDemoAccounts
    {
        public int Id { get; set; }
        public int GameDemoId { get; set; }
        public string SystemName { get; set; }
        public string Url { get; set; }
        public string UName { get; set; }
        public string Pwd { get; set; }
        public string City { get; set; }
        public string CurrentPlayer { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
    }
}
