//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class GameDemoRecharge
    {
        public int Id { get; set; }
        public int GameDemoId { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public int Pay { get; set; }
        public string Memo { get; set; }
        public string Reason { get; set; }
        public System.DateTime InTime { get; set; }
        public int State { get; set; }
    }
}
