//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Gift
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Price { get; set; }
        public string State { get; set; }
        public System.DateTime Intime { get; set; }
        public string Explain { get; set; }
        public Nullable<int> OldPrice { get; set; }
        public string Color { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Imgs { get; set; }
        public string Msgs { get; set; }
    }
}
