//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class OpenService
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string GameName { get; set; }
        public System.DateTime StartTime { get; set; }
        public string Url { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string Rec_Hot { get; set; }
        public System.DateTime Rec_Datetime { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public string CheckName { get; set; }
        public string ServerName { get; set; }
    }
}
