//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Num { get; set; }
        public string color { get; set; }
        public string Address_Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string state { get; set; }
        public string Type { get; set; }
        public string Order_Num { get; set; }
        public System.DateTime InTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public int IsDel { get; set; }
        public string Logo { get; set; }
    }
}
