//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Recharge
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> Num { get; set; }
        public int Used { get; set; }
        public string Remark { get; set; }
        public System.DateTime InTime { get; set; }
        public string ComboName { get; set; }
    }
}
