//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class UserMessage
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Msg { get; set; }
        public int State { get; set; }
        public System.DateTime InTime { get; set; }
        public string PayType { get; set; }
        public int Pay { get; set; }
        public string IsDel { get; set; }
        public string Memo { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string orderNo { get; set; }
    }
}
