//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class UserRaiders
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string GameName { get; set; }
        public string Title { get; set; }
        public string EditTitle { get; set; }
        public string Key { get; set; }
        public string Msg { get; set; }
        public string Reason { get; set; }
        public System.DateTime InTime { get; set; }
        public string State { get; set; }
        public string Rec { get; set; }
        public System.DateTime Rec_Time { get; set; }
        public string Rec_Hot { get; set; }
        public Nullable<System.DateTime> Rec_Hot_Time { get; set; }
        public string CheckName { get; set; }
        public string Source { get; set; }
        public string Memo { get; set; }
        public string Editor { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Tip { get; set; }
        public Nullable<int> Stamp { get; set; }
    }
}
